"use client";

import {
  Boxes,
  CheckCircle,
  Clock,
  AlertTriangle,
  Download,
} from "lucide-react";

const recentReports = [
  {
    id: 1,
    title: "Asset Allocation Report",
    generatedBy: "Admin",
    date: "12 Jul 2026",
    status: "Generated",
  },
  {
    id: 2,
    title: "Maintenance Summary",
    generatedBy: "Rahul Sharma",
    date: "11 Jul 2026",
    status: "Generated",
  },
  {
    id: 3,
    title: "Audit Report",
    generatedBy: "Priya Patel",
    date: "10 Jul 2026",
    status: "Pending",
  },
];

export default function ReportsPage() {
  return (
    <div className="space-y-6">

      {/* Header */}

      <div className="flex items-center justify-between">

        <div>

          <h1 className="text-3xl font-bold text-slate-800">
            Reports
          </h1>

          <p className="mt-1 text-slate-500">
            View organization reports and analytics.
          </p>

        </div>

        <button className="flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-white hover:bg-indigo-700">

          <Download size={18} />

          Export Report

        </button>

      </div>

      {/* Statistics */}

      <div className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-4">

        <div className="rounded-2xl border bg-white p-6 shadow-sm">

          <Boxes className="mb-3 text-indigo-600" />

          <p className="text-slate-500">
            Total Assets
          </p>

          <h2 className="mt-2 text-3xl font-bold">
            124
          </h2>

        </div>

        <div className="rounded-2xl border bg-white p-6 shadow-sm">

          <CheckCircle className="mb-3 text-green-600" />

          <p className="text-slate-500">
            Allocated
          </p>

          <h2 className="mt-2 text-3xl font-bold">
            68
          </h2>

        </div>

        <div className="rounded-2xl border bg-white p-6 shadow-sm">

          <Clock className="mb-3 text-blue-600" />

          <p className="text-slate-500">
            Available
          </p>

          <h2 className="mt-2 text-3xl font-bold">
            46
          </h2>

        </div>

        <div className="rounded-2xl border bg-white p-6 shadow-sm">

          <AlertTriangle className="mb-3 text-red-600" />

          <p className="text-slate-500">
            Maintenance
          </p>

          <h2 className="mt-2 text-3xl font-bold">
            10
          </h2>

        </div>

      </div>

      {/* Recent Reports */}

      <div className="overflow-hidden rounded-2xl border bg-white shadow-sm">

        <div className="border-b px-6 py-4">

          <h2 className="text-xl font-semibold">
            Recent Reports
          </h2>

        </div>

        <table className="w-full">

          <thead className="bg-slate-50">

            <tr>

              <th className="p-4 text-left">
                Report
              </th>

              <th className="p-4 text-left">
                Generated By
              </th>

              <th className="p-4 text-left">
                Date
              </th>

              <th className="p-4 text-left">
                Status
              </th>

            </tr>

          </thead>

          <tbody>

            {recentReports.map((report) => (

              <tr
                key={report.id}
                className="border-t hover:bg-slate-50"
              >

                <td className="p-4 font-medium">
                  {report.title}
                </td>

                <td className="p-4">
                  {report.generatedBy}
                </td>

                <td className="p-4">
                  {report.date}
                </td>

                <td className="p-4">

                  <span
                    className={`rounded-full px-3 py-1 text-xs font-semibold ${
                      report.status === "Generated"
                        ? "bg-green-100 text-green-700"
                        : "bg-yellow-100 text-yellow-700"
                    }`}
                  >
                    {report.status}
                  </span>

                </td>

              </tr>

            ))}

          </tbody>

        </table>

      </div>

    </div>
  );
}